version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "hennesk"
    ignore:
      - dependency-type: development
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "hennesk"
    ignore:
      - update-types: ["version-update:semver-major"]